spring.application.name=ProyectoBookVerseDanielMejias2
server.port=8080

spring.datasource.url=jdbc:h2:mem:bookversedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Habilita la consola web para ver las tablas en el navegador(bbdd)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# Cada vez que la aplicacion web se inicia, empieza vacia y luego la crea
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect